# Generated by Django 5.1.4 on 2024-12-10 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('days_since_watered', models.IntegerField(default=0)),
                ('frequency', models.IntegerField()),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.garden')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('days_since_planted', models.IntegerField()),
                ('days_until_mature', models.IntegerField()),
                ('description', models.TextField(max_length=250)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.plot')),
            ],
        ),
    ]
