# Generated by Django 5.1.4 on 2024-12-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
    ]
