# Generated by Django 5.1.4 on 2024-12-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_plant_days_since_planted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='frequency',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plant',
            name='days_since_planted',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plant',
            name='days_until_mature',
            field=models.IntegerField(),
        ),
    ]
